### ISSUE TITLE
Incorrect type generation with optional route parameters

### ISSUE THREAD

**Issue by vwong** [marko-js/run#45]
In `marko/run@0.2.1`, I have a route `aaa.$aId.(,bbb.$bId).(,ccc.$cId)+page.marko` in order to support the URL structure:

```
/aaa/$aid/ccc/$cid
/aaa/$aid/bbb/$bid/ccc/$cid
/aaa/$aid/bbb/$bid
/aaa/$aid
```

This results in 4 permutations generated in `.marko-run/routes.d.ts` below, which confuses the typechecking of `$global.params`. Deleting the 3 shorter permutations calms Typescript down.

```
declare module "../src/routes/aaa.$aid.(,bbb.$bid).(,ccc.$cid)+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/aaa/:aid"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/aaa.$aid.(,bbb.$bid).(,ccc.$cid)+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/aaa/:aid/bbb/:bid"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/aaa.$aid.(,bbb.$bid).(,ccc.$cid)+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/aaa/:aid/bbb/:bid/ccc/:cid"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/aaa.$aid.(,bbb.$bid).(,ccc.$cid)+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/aaa/:aid/ccc/:cid"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export const route: Run.HandlerTypeFn<Route>;
  }
}
```

**Comment by rturnq** [comment]
Thanks for the report, this should be fixed in 0.2.2.

The types for a page or handler that supports multiple routes will now be the union of all the routes they support, similar to how middleware and layouts worked.

**Comment by vwong** [comment]
Hmm, 0.2.2 looks like it should work. Yet `mtc` complains differently now:

```
src/routes/aaa.$aid.(,bbb.$bid).(,ccc.$cid)+page.marko:2:18 - error TS2339

  1 | $ const {
> 2 |   params: { aid, bid, cid },
    |                  ^^^ Property 'bid' does not exist on type '{ aid: string; } | { aid: string; bid: string; } | { aid: string; bid: string; cid: string; } | { aid: string; cid: string; }'.
  3 | } = $global;
  4 |
  5 | $ console.log({ aid, bid, cid })

src/routes/aaa.$aid.(,bbb.$bid).(,ccc.$cid)+page.marko:2:23 - error TS2339

  1 | $ const {
> 2 |   params: { aid, bid, cid },
    |                       ^^^ Property 'cid' does not exist on type '{ aid: string; } | { aid: string; bid: string; } | { aid: string; bid: string; cid: string; } | { aid: string; cid: string; }'.
  3 | } = $global;
  4 |
  5 | $ console.log({ aid, bid, cid })
```

**Comment by vwong** [comment]
@rturnq Should I raise a separate issue with `mtc` there? Or do you think the remaining issue is in this repo?

**Comment by rturnq** [comment]
This is expected (though not ideal) because the type of `MarkoRun.Context` for this page will be a union of all the routes it handles. Without discriminating the union TypeScript then only knows the parameters which are available to all union members. You can discriminate using the `route` property and the params will be narrowed

```ts
$ {
  if ($global.route === '/aaa/:aId') {
    $global.params.aId //string
    $global.params.bId //undefined
    $global.params.cId //undefined
  } else if ($global.route === '/aaa/:aId/bbb/:bId') {
    $global.params.aId //string
    $global.params.bId //string
    $global.params.cId //undefined
  }
}
```

This was originally designed to support layouts and middleware where this type of discrimination would make more sense but I see how it is quite inconvenient here.

I think we can do better by typing the params as a superset where in each union member the missing params would be typed as `undefined`. This should allow everything to narrow as it currently does and also give access to the non-narrowed types as `string | undefined`.

I'll re-open this issue and try to get a fix out soon.

P.S. Meta data will have the same problem but I'm not sure what can be done for that at the moment. We are thinking about forcing meta data to be objects and allowing them to be defined anywhere and merged together. If we did that I think this same change could work for meta as well.

**Comment by vwong** [comment]
Thanks for looking into this. I look forward to the fix.

I learnt something new... I don't usually do unions of interfaces, only basic types
> Without discriminating the union TypeScript then **only knows the parameters which are available to all union members**
